# supported versions here: https://hub.docker.com/_/rust
ARG RUST_BUILDER_VERSION=slim-bookworm
ARG UBUNTU_RELEASE_VERSION=noble

########################
## builder image
########################
FROM rust:${RUST_BUILDER_VERSION} AS builder

RUN apt-get update \
    && apt-get -y install git build-essential cmake libclang-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /rettid

# download (most) dependencies in their own layer
COPY Cargo.lock Cargo.toml ./
RUN mkdir src && echo "fn main() { panic!(\"why am i running?\") }" > src/main.rs
RUN cargo build --release --locked --bin rettid
RUN rm ./src/main.rs && rmdir ./src

# copy the source and build the rettid binary
COPY . ./
RUN cargo build --release --locked --bin rettid
RUN echo "finished building rettid!"

########################
## release image
########################
FROM ubuntu:${UBUNTU_RELEASE_VERSION} AS release

# Import rettid binary from builder
COPY --from=builder /rettid/target/release/rettid /usr/local/bin/rettid

# Add non-root user for running rettid
RUN useradd \
    --no-create-home \
    --password "!" \
    --comment "user for running rettid" \
    rettid
USER rettid

# Document that we intend to expose port 8080 to whoever runs the container
EXPOSE 8080

# Run a healthcheck every minute to make sure rettid is functional
HEALTHCHECK --interval=1m --timeout=3s CMD wget --spider -q http://localhost:8080/settings || exit 1

# Add container metadata
LABEL org.opencontainers.image.authors="gbrunoo"

CMD ["rettid"]
